name: Build and Push Docker Image
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v2
      
      # Install hadolint
      -
        name: Install hadolint
        run: |
          sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod +x /usr/local/bin/hadolint
      
      # Run hadolint on Dockerfile
      -
        name: Lint Dockerfile
        run: |
          hadolint Dockerfile
        continue-on-error: true  # Continue even if hadolint finds issues

  docker:
    runs-on: ubuntu-latest
    needs: lint  
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: alexisu7/efrei-devops-tp2:1.0.0
